[IV-24-25] Objetivo 0
Carlosmapego8/GoMountain pull request #1
Opened 2024-09-30 18:53 UTC by Carlosmapego8

- [✔️]  ¿Se trata de un problema real del que se tenga conocimiento personal?
Sí puesto que, como explico, hago deporte en la naturaleza y cuando voy a un sitio que no conozco me encuentro este problema. 

- [✔️]  ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
Sí, ya que al estar en un entorno natural te permitiría acceder a los datos de las rutas en cualquier momento desde cualquier lugar y de forma inmediata.

- [✔️]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
Sí, es necesaria a la hora de comparar y analizar la información relevante para cada ruta.

- [✔️]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el README?

- [✔️]  ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?
Es necesario obtener los datos públicos de las aplicaciones mencionadas, el usuario solo deberá introducir la zona sobre la que quiere que se le muestre información.

- [✔️]  ¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo?
He seguido la lista de comprobación.

2024-10-04 15:07 UTC, JJ commented
> * [✔️]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Sí puesto que, como explico, hago deporte en la naturaleza y cuando voy a un sitio que no conozco me encuentro este problema.
> 
>     * [✔️]  ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
>       Sí, ya que al estar en un entorno natural te permitiría acceder a los datos de las rutas en cualquier momento desde cualquier lugar y de forma inmediata.
> 
>     * [✔️]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
>       Sí, es necesaria a la hora de comparar y analizar la información relevante para cada ruta.
> 
>     * [✔️]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el README?

¿Qué configuración crees que has incluido y cómo la has enlazado?

2024-10-04 15:12 UTC, JJ requested changes
¿De qué forma el proyecto presentado por un estudiante el año pasado, mencionando incluso las mismas páginas, y que comenté en clase en el hackatón, es un proyecto personal?
Es imprescindible que se trate de proyecto personal, simplemente porque sólo una persona que esté involucrada en un proyecto tendrá las respuestas cuando se planteen una serie de preguntas. Y porque se trata de que apliquéis una metodología para encontrar ese proyecto personal, no que pongáis un proyecto que hayáis encontrado. Y dado que sólo se cumple el objetivo si se sigue la metodología (no si se pone un problema que ya se aprobó en años anteriores), te rogaría que en tu próxima entrega especificaras claramente cómo has seguido la metodología de *design thinking* para llegar a un problema que plantear para la asignatura.

2024-10-08 06:59 UTC, JJ commented
No me has pedido revisión, pero no vayas por ahí, por favor. Mira [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#en-el-contenido):

> Los deseos del cliente son órdenes, y eso significa que si el cliente quiere que vuestra aplicación haga algo, tendréis que testear que efectivamente lo hace. Si el problema es maximizar ventas, tendréis que examinar cuales son las ventas con el método actual (o aleatorio, lo que sea) y después con vuestro algoritmo, y ver que es superior estricto. Si queréis predecir, tendréis que programar vosotros un algoritmo que prediga y comprobar con datos que efectivamente lo hace.

Y si queréis "recomendar", tendréis que comprobar que efectivamente le gusta al usuario. Lo que es imposibl, claro, por no mencionar que *tampoco* tenéis los datos de las películas ni podéis pedirle al usuario datos excesivos (qué te gusta, qué has visto, etcétera)

2024-10-08 07:03 UTC, Carlosmapego8 commented
@JJ ya he cambiado el problema a uno más personal aún. Para encontrarlo he estado pensando en algo que día a día me pase con frecuencia y una solución que me gustaría tener para ayudarme

2024-10-08 07:07 UTC, JJ commented
Por favor, lee lo que he escrito 4 minutos antes de que pidas revisión.

2024-10-08 07:08 UTC, JJ commented
> @JJ los datos de las películas son públicos en la BBDD de IMDB y las votaciones también, con eso se podría saber si se ha visto o no y qué le gusta y qué no. Es una recomendación basada en las votaciones pasadas creando así un perfil de usuario

Todavía tendrías que:
1. Pedir al usuario una cantidad de información ingente
2. Programar el algoritmo de recomendación
3. Incluso con eso, no tendrías manera de saber si al usuario le ha gustado o no la película que le recomiendes, porque por definición es una película que no ha visto. Dado que es así, los tests en el objetivo 4 no podrían de ninguna manera seguir las historias de usuario (porque simplemente es imposible) sino que se limitarían a comprobar que el algoritmo saca algo que es lo que tú quieres que saque desde el principio.

2024-10-08 07:10 UTC, JJ commented
Y si lo que quieres es hacerlo *solo* para usuarios de IMDB, esa información creo que no es pública, si lo es está a través del API, y *no se puede usar un API externo* (como dice en el guión)

2024-10-08 07:59 UTC, Carlosmapego8 commented
@JJ Revisión

2024-10-08 11:09 UTC, JJ requested changes
Creo que ya te lo he mencionado, pero aquí la metodología que hay que seguir es design thinking aplicado a uno mismo o a un conocido para encontrar un problema con el que poder trabajar, y que además se adapte a esta asignatura. Permíteme que dude que esto sea un problema cotidiano, porque si acaso te compras un reloj cada ddos o tres años (como cualquier hijo de vecino).
La metodología de "voy a buscar problemas por ahí a ver si cuela" ya has visto que es poco efectiva. O no es un problema que tenga una lógica de negocio sustancial, o no entiendes realmente el problema, o simplemente no se adapta a esta asignatura.
Ya la has intentado tres veces y parece que no ha tenido el éxito deseado. Precisamente por eso se propone el uso de metodologías en ingeniería del software, como design thinking para desarrollo de producto. El problema que se encuentre puede ser adecuado para una startup que se venda por un millón, o simplemente para avanzar en esta asignatura, porque al empatizar entiendes el problema, y al entender el mismo puedes formular el resto de los elementos y metodologías que se van a usar: historias de usuario, productos mínimamente viables, y demás. 
Pero es que además [te dije aquí](https://github.com/Carlosmapego8/GoMountain/pull/1#pullrequestreview-2348321155) que debías seguir explícitamente esa metodología y documentar como lo has hecho. Te rogaría que lo hicieras así, y que hasta que no lo hagas, no solicites de nuevo revisión.
Sigues sin incluir la configuración del repositorio y enlazarla, *a pesar de que has marcado que sí*. Leer tanto el guión como seguir la lista de comprobación y no marcarlo todo también es esencial para poder superar este objetivo.

2024-10-08 11:09 UTC, JJ commented on README.md
> +Como corredor que soy, siempre me gusta llevar la mejor tecnología en mi muñeca cuando salgo a correr, sin embargo, el comprar relojes específicos de running puede llegar a ser muy costoso. Por otra
Una búsqueda de Google te devuelve los precios de cualquier artículo en muchas redes de ventas. Pero vamos a suponer que no es así y que efectivamente hay ese problema...

2024-10-08 11:09 UTC, JJ commented on README.md
> +Aplicación que compare por ti los precios de uno o varios relojes deportivos en las principales webs de venta de deporte y, en caso de bajar hasta un precio deseado, envíe una notificación por correo
"Comparar" no es una lógica de negocio suficiente. Como dice [el guión](https://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n), 

> ¿Por es necesario que la lógica de negocio ser no trivial?

> Porque el estudiante tiene que programar esa lógica de negocio en los tests de los objetivos a partir del cuatro. Si es trivial, ni siquiera requiere tests; si es de almacena y busca, ni siquiera es lógica de negocio.

Supongo que la cosa no va por ahí, aunque no está claro, sino que lo que quieres es hacer scraping de diferentes páginas web de ventas. Comprobarás que no es sencillo, ni siquiera de la más simple, precisamente para evitar comparaciones. Y si lo fuera, verás que es prácticamente imposible comprar por nombre y modelo dos items que aparezcan en dos webs diferentes.

Si no fuera así, podría haber un problema para trabajar con él. Pero me temo que no es el caso.

2024-11-04 18:29 UTC, Carlosmapego8 commented
@JJ revisión

2024-11-04 18:34 UTC, JJ requested changes
El énfasis es que trabajéis en un proyecto *personal*. No hay ninguna constancia que se trate de ello. Y se pide así para que se aprenda a usar metodologías, en este caso de *design thinking* para descubrir qué problema tiene alguien y empezar a poder describirlo, que es parte de la solución.

2024-11-04 18:51 UTC, Carlosmapego8 commented
Como bien digo en el cuerpo del PR mi madre trabaja dentro de una residencia y en muchas ocasiones sufre cambios de última hora, tener que trabajar más horas de lo establecido, no poder prever con tiempo cuándo coger vacaciones,...

> El énfasis es que trabajéis en un proyecto _personal_. No hay ninguna constancia que se trate de ello. Y se pide así para que se aprenda a usar metodologías, en este caso de _design thinking_ para descubrir qué problema tiene alguien y empezar a poder describirlo, que es parte de la solución.

He añadido más en detalle el por qué se quiere hacer este desarrollo. Pero en resumen, es por la falta de organización entre todos los compañeros y que muchas veces los horarios no tienen en cuenta muchos casos que se pueden dar, generando problemas entre los compañeros

2024-11-04 19:27 UTC, JJ requested changes
Conviene que desde el principio entiendas la dinámica que incluye responder a todos los comentarios cambiando el contenido del PR.

2024-11-04 19:27 UTC, JJ commented on README.md
> +Normalmente, esta planificación se realiza una vez y es conocida de antemano, sin embargo, esta forma de trabajar es poco flexible a imprevistos, vacaciones, días de asuntos propios,... en definitiva
Por favor, mira y responde a todos los comentarios.

2024-11-04 19:36 UTC, Carlosmapego8 commented
Realmente no entiendo qué es lo que quiere que haga, lo primero que he hecho ha sido editar el PR respondiendo a todas las preguntas planteadas para este objetivo.
> Conviene que desde el principio entiendas la dinámica que incluye responder a todos los comentarios cambiando el contenido del PR.

En las anteriores ocasiones podía llegar a ver el problema que tenía mi entrega. Pero en este caso no soy capaz de verlo. No sé si podría ser más preciso. Gracias.

2024-11-04 19:54 UTC, JJ commented
Sólo hay que describir el problema. ¿Has leído donde pone [en los errores frecuetnes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md):

> Si se describe lo que el cliente quiere hacer sin decir por qué quiere hacerlo, no estás describiendo el problema, estás describiendo una solución. 

Solo hay que describir la solución como dice [en el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#tldr):

> en caso de que no esté claro a partir de la descripción qué tipo de soluciones se tienen en mente, hay que describir la lógica de negocio, que es el código propio que resuelve el problema.

2024-11-05 06:26 UTC, Carlosmapego8 commented
Ya he actualizado de nuevo. Solo se queda la descripción del problema sin detallar qué solución se tiene en mente. @JJ

2024-11-05 06:59 UTC, JJ approved these changes
:+1:

2024-11-05 07:01 UTC, merged