[IV-24-25] Objetivo 1
Carlosmapego8/GoMountain pull request #4
Opened 2024-11-05 19:24 UTC by Carlosmapego8

✅ ¿Las historias de usuario y los milestones constituyen una guía
suficiente para poder comenzar el desarrollo de un proyecto?
 ✅ ¿Los milestones están ordenados correctamente, de forma que el 1 o
0 sea lo primero que hay que empezar a publicar?
✅ ¿Todos los milestones se construyen sobre el anterior, teniendo un
orden lógico el desarrollo?
✅ ¿El milestone 0 tiene asignada alguna historia de usuario?
✅ ¿El milestone 0 corresponde con lo mencionado varias veces en
clase, y en concreto con lo que se solicita en el objetivo
siguiente?
✅ ¿Todos los milestones describen correctamente un producto y qué
lo hace válido, y no un concepto vago, una funcionalidad o una tarea?
✅ ¿Los milestones son graduales, o hay un salto grande entre ellos?
✅ ¿Los milestones iniciales son internos, y hay a continuación milestones o
productos externos?
✅ ¿Los milestones son mínimos, es decir, incluyen un producto
mínimamente viable para poder avanzar?
✅ ¿El milestone 0 es mínimo y viable?
✅ ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
cada hito?
✅ ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
contrario podrían desarrollarse muchas posibles etapas internas o externas
de un proyecto?
✅ ¿He tenido en cuenta en las historias de usuario que se trata de un
proyecto que se desplegará en la nube?
✅ ¿Están descritos todos los conceptos mencionados en las HUs con
suficiente claridad, generalmente en documentos aparte?
✅ ¿Tienen coherencia suficiente las historias de usuario, y en caso
de que no lo tengan, se ha escrito un user journey para
aclararlo?
✅ ¿Todas las historias de usuario representan un beneficio para el
mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
desean hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2024-11-08 10:47 UTC, adiazcencillo reviewed
Se me ha asignado tu PR para revisión. Te dejo algunos comentarios.

2024-11-08 10:47 UTC, adiazcencillo commented on docs/milestones.md
> ++ **Objetivo**: Analizar las historias de usuario para modelar el sistema básico para asignación de turnos.
Recuerda que en un milestone estás definiendo un PMV junto con criterios de viabilidad, por lo que usar la palabra _Objetivo_ para describir el producto puede ser confuso para el desarrollador.

2024-11-08 10:47 UTC, adiazcencillo commented on docs/milestones.md
> ++ **Objetivo**: Analizar las historias de usuario para modelar el sistema básico para asignación de turnos.
Te adjunto un estracto de los errores frecuentes del objetivo 1:

* Aunque los milestones en principio no tienen por qué tener información sobre
  las historias de usuario, si hay varias historias de usuario hablar de "modelo
  del problema" o de "lógica de negocio" no es suficiente, porque las dos
  historias de usuario (o las 5) pueden tener diferentes aspectos del problema,
  o incluso ser problemas diferentes. En todo caso, siempre es conveniente ser
  preciso en el lenguaje, porque en el momento que se vaya a trabajar con un
  milestone determinado puede haber más historias de usuario, o menos, así que
  aclarar a qué parte del problema del cliente se circunscribe siempre es
  conveniente.
  - De la misma forma, enlazar *todas* las historias de usuario sólo indica
    dejadez y falta de precisión a la hora de indicar a la persona que trabaje
    qué es lo que debe hacer.

Es conveniente que indiques concretamente las historias de usuario que definen los problemas que quieres modelar mediante tu PMV, ya que como se dice arriba, apelar a _todas_ las HUs puede ser confuso por la variedad de problemas que estas plantean.

2024-11-11 10:38 UTC, Carlosmapego8 commented on docs/milestones.md
> ++ **Objetivo**: Analizar las historias de usuario para modelar el sistema básico para asignación de turnos.
Corregido en [f3849ed](https://github.com/Carlosmapego8/GoMountain/pull/4/commits/f3849edba6e3e5dfd948e7527519f3471a64d735)

2024-11-11 10:52 UTC, adiazcencillo reviewed
No te olvides de resolver los comentarios! Ánimo :)

2024-11-11 10:52 UTC, adiazcencillo commented on docs/milestones.md
> ++ **Validación**: Se considerará validado mediante pruebas en conjuntos de datos de prueba, asegurando una correcta asignación de turnos.
En el M0 defines un PMV que es el modelo del problema descrito en #2. El criterio para considerar dicho modelo válido, según dices, es que pase algunos tests, pero, ¿cómo se pueden definir tests para probar un modelo? Dale una vueltecilla al criterior de validez, y con eso tendrías mi aprobación.

2024-11-11 11:12 UTC, Carlosmapego8 commented on docs/milestones.md
> ++ **Validación**: Se considerará validado mediante pruebas en conjuntos de datos de prueba, asegurando una correcta asignación de turnos.
Corregido en [948ed5a](https://github.com/Carlosmapego8/GoMountain/pull/4/commits/948ed5ac481a8e6dc5b31fa1761384d05c097af1)

2024-11-12 17:16 UTC, Carlosmapego8 commented
@JJ revision

2024-11-12 19:13 UTC, JJ requested changes
Conviene que tratéis de comprender qué es lo que estáis haciendo y por qué. Revisa los errores frecuentes y el guión.

2024-11-12 19:13 UTC, JJ commented on .gitignore
Por favor, no incluyáis en el PR si no se tiene que evaluar. Sólo introduce ruido y más trabajo a la hora de hacerlo. Cámbialo en main y haz un rebase.

2024-11-12 19:13 UTC, JJ commented on docs/milestones.md
> ++ **Descripción del producto**: Analizar [HU001](https://github.com/Carlosmapego8/GoMountain/issues/2) para modelar el sistema básico para asignación de turnos.
¿El producto es "analizar"? ¿Eso es un producto o una tarea?
Si ya sabes que el modelo es "el sistema básico de asignación de turnos", ¿por qué necesitas un milestone? ¿O una historia de usuario?

2024-11-12 19:58 UTC, Carlosmapego8 commented on docs/milestones.md
> ++ **Descripción del producto**: Analizar [HU001](https://github.com/Carlosmapego8/GoMountain/issues/2) para modelar el sistema básico para asignación de turnos.
Corrijo en [a57a0cb](https://github.com/Carlosmapego8/GoMountain/pull/4/commits/a57a0cbc8c8c8cc941a22994fe99618a11903566)

2024-11-13 06:22 UTC, Carlosmapego8 commented
@JJ ya he revisado, creo que ahora sí, revisión
> Revisa los errores frecuentes y el guión.

2024-11-13 07:07 UTC, JJ requested changes
Te pediría que en esta ocasión reflexionaras sobre los conceptos que están en juego en este objetivo, leyeras los documentos mencionados y actuaras en consecuencia.

2024-11-13 07:07 UTC, JJ commented on docs/milestones.md
> ++ **Descripción**: Analizar las historias de usuario para modelar los elementos fundamentales del dominio.
En general, cuando una persona solicita revisión poco tiempo después de una evaluación en la cual hay errores conceptuales graves, es porque tratar de entender cuál es el problema y actuar en consecuencia no es algo que entre en sus cálculos. En consecuencia, a veces también se entiende mal o superficilamente lo que se dice en el comentario y se actúa de peor forma todavía.
En la corrección en esta línea te dije:
> ¿El producto es "analizar"? ¿Eso es un producto o una tarea?

Como consecuencia, has borrado "producto". ¿Has entendido lo que es un milestone? ¿Crees que borrar "producto " refleja mejor el concepto de milestone que tú tienes? Entiendo que es así, puesto que es lo que has hecho.

Adicionalmente, has cambiado "el sistema básico para asignación de turnos" por "elementos fundamentales del dominio". Al menos has borrado "asignación de turnos"... pero como lo has hecho a toda prisa y por lo que he dicho en el comentario, *no has aplicado lo mismo en el siguiente milestone*. 

En todo caso, ¿"elementos fundamentales del dominio" qué son? Si alguien te indica que ese es el PMV que quiere, ¿qué le vas a entregar? 

Si no entiendes lo que es un modelo de problema, trata de entenderlo. No se trata de que combinéis palabras y frases hasta que déis con la tecla, sino que entendáis qué pasos hay que dar para desarrollar un producto y la importancia que tiene cada uno de los pasos.

Por si fuera poco, has cambiado una historia de usuario concreta por "las historias de usuario". ¿Has leído los errores frecuentes?

2024-11-13 08:36 UTC, Carlosmapego8 commented
@JJ Creo que entiendo lo que es un modelo de problema, de todas formas lo he dejado más aclarado ahora
>Si no entiendes lo que es un modelo de problema, trata de entenderlo

He leído los errores frecuentes, de hecho eso lo cambié gracias a las correcciones de mi compañero, pero al hacer el rebase no me di cuenta que eso volvió al estado anterior. Disculpe
>Por si fuera poco, has cambiado una historia de usuario concreta por "las historias de usuario". ¿Has leído los errores frecuentes?

2024-11-14 11:41 UTC, Carlosmapego8 commented
@JJ revision

2024-11-14 12:44 UTC, JJ commented
¿Sabes cuantas entregas de este objetivo contienen la palabra "Analizar"? ¿Sabes qué le he dicho a cada una de ellas?

2024-11-14 15:01 UTC, Carlosmapego8 commented
@JJ revision

2024-11-18 06:25 UTC, JJ requested changes
Ex *extremadamente conveniente* que sepas lo que pides. Si no seguimos con el juego de sillas musicales donde cambias unas palabras por otras, sin demostrar que se entienda el concepto que hay detrás. Y si no se entiende es imposible que se exija a la persona que vaya a trabajar en tu repositorio.

2024-11-18 06:25 UTC, JJ commented on docs/milestones.md
> ++ **Entregable**: Código, sin implementación, de las clases que serán necesarias para la futura implementación de la lógica de negocio.
¿Clases o estructuras de datos?

2024-11-18 06:25 UTC, JJ commented on docs/milestones.md
> ++ **Descripción**: Definir las estructuras de datos que se utlizarán durante el proyecto. Obteniendo la representación de lo planteado en [HU001](https://github.com/Carlosmapego8/GoMountain/issues/2)
¿Solo las estructuras de datos? ¿O las clases ocmo dices más abajo? ¿Las que se *utilizarán* o tienen que seguir algún otro criterio? ¿La *representación* es el *modelo*?

2024-11-18 17:54 UTC, JJ commented
> @JJ en [a87caa1](https://github.com/Carlosmapego8/GoMountain/pull/4/commits/a87caa1d42bf65d3faf0a1bda5cd8f93420dbe75) dejo todo el Milestone mucho más aclarado con lo que se pide. En los otros 2 entiendo que estaba bastante claro. Disculpa por el lío y gracias por la revisión

Nadie ha dicho que estén aclarados. Al contrario, te he dicho que leas los errores frecuentes. ¿Lo has hecho? ¿Qué dice sobre más de 2 milestones? ¿Y sobre cosas que puedes haber puesto o no en los milestones que no se han evaluado?

2024-11-18 17:55 UTC, JJ commented
Por cierto, no lo habrás leído, porque es nuevo, pero lee también [el segundo error frecuente de este apartado](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md#sobre-los-milestones)

2024-11-18 18:21 UTC, Carlosmapego8 commented
@JJ me refería a que para mí queda más claro que antes lo que estoy pidiendo.
>Nadie ha dicho que estén aclarados. 
He vuelto a leer de nuevo los errores frecuentes y modificado de nuevo con como creo que debería quedar para evitar todos los errores especificados.

2024-11-19 06:39 UTC, JJ requested changes
Te señalaría de nuevo los [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md#sobre-los-milestones), incluyendo donde dice:

> Si se dice qué forma debe tener un PMV, ni se deja al desarrollador trabajar sobre el mismo, ni de hecho hace falta que se haga ese trabajo, porque ya se ha hecho. Se debe decir la forma general del producto o qué tiene que hacer el producto para ser válido, no qué contiene, porque para eso es mejor que lo haga directamente quien lo dice.

2024-11-19 06:39 UTC, JJ commented on docs/milestones.md
> ++ **Entregable**: Código, sin implementación, de las componentes de código (clases, funciones, ...) que serán necesarias para la futura implementación de la lógica de negocio y que representen el mod
Os agradecería mucho que leyérais lo que escribís. ¿Crees que "Código, sin implementación, de las componentes de código (clases, funciones, ...) que serán necesarias para la futura implementación" se entiende? ¿Qué es "código sin implementación"? ¿Qué son "las componentes de código"? ¿Si lees "Funciones"... "para la futura implementación de la lógica de negocio" qué es lo que entiendes? Y si además lo tienes que hacer "sin implementación", ¿qué es lo que hay que hacer de forma precisa?

2024-11-19 06:39 UTC, JJ commented on docs/milestones.md
> ++ **Entregable** : Código que implimente la lógica de negocio respetando las restricciones indicadas en [HU001](https://github.com/Carlosmapego8/GoMountain/issues/2) (reparto equitativo, horas máxima
Si ya sabes que tiene que respetar esas restriciones, ¿para qué quieres la historia de usuario? ¿Y el milestone?

2024-11-19 07:48 UTC, Carlosmapego8 commented on docs/milestones.md
> ++ **Entregable** : Código que implimente la lógica de negocio respetando las restricciones indicadas en [HU001](https://github.com/Carlosmapego8/GoMountain/issues/2) (reparto equitativo, horas máxima
Ya he quitado esas especificación de las restricciones, entiendo que no hay que ser tan específico

2024-11-19 07:50 UTC, Carlosmapego8 commented on docs/milestones.md
> ++ **Entregable**: Código, sin implementación, de las componentes de código (clases, funciones, ...) que serán necesarias para la futura implementación de la lógica de negocio y que representen el mod
Con código sin implementación quiero referirme a simplemente a la definición de las clases, funciones, variables o cualquier cosa que se vaya a utilizar en la futura implementación. De todas formas, he cambiado esa parte para dejarlo más abierto para que el desarrollador pueda trabajar sobre el mismo.

2024-11-19 07:51 UTC, Carlosmapego8 commented
@JJ solicito revisión

2024-11-19 07:55 UTC, JJ approved these changes
Si los UJ complementan a las HU, incorporálos a las mismas cuando vayas a trasladarlo a GitHub. Recuerda que tienes que poner los milestones e HUs *tal como están aprobados* en GitHub.

2024-11-19 07:55 UTC, JJ commented on docs/user_journey.md
> +Antonio planifica los turnos semana a semana, en los ratos libres que tiene en el finde semana porque durante la semana le consume un tiempo del que no dispone. Revisa manualmente los horarios, cambi
Los UJ, como todo lo demás, tiene una función. Si los pones aisladamente, sin ningún tipo de relación con el resto de los documentos, ¿crees que sirven de algo?

2024-11-19 08:15 UTC, Carlosmapego8 commented on docs/user_journey.md
> +Antonio planifica los turnos semana a semana, en los ratos libres que tiene en el finde semana porque durante la semana le consume un tiempo del que no dispone. Revisa manualmente los horarios, cambi
Les he añadido a cada UJ su HU correspondiente en [1f59f6d](https://github.com/Carlosmapego8/GoMountain/pull/4/commits/1f59f6d52b7414f472e1c15875e3aa6c3c7336e4)

2024-11-19 08:18 UTC, Carlosmapego8 commented
@JJ he añadido el enlace a cada HU dentro de cada UJ
>Recuerda que tienes que poner los milestones e HUs tal como están aprobados en GitHub.

No sé si con eso te refieres a algo más. 

Por otra parte, he visto que en el repo principal has dado como válido este objetivo. Entiendo que ya puedo mergear el PR, aunque espero que me confirmes

2024-11-19 08:20 UTC, JJ commented
Me refiero a que ahora @FerniCuesta va a trabajar con los issues y milestones en GitHub, no en el texto, así que eso es lo que tienes que poner ahí.

2024-11-19 08:39 UTC, Carlosmapego8 commented
Ya he actualizado las HU añadiéndoles los UJ correspondientes

2024-11-21 18:26 UTC, merged